version: '3'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"


  redis:
    image: redis
    ports:
      - "6379:6379"

  rest-api:
    build: .
    image: rest-api
    environment: 
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/db
      - REDIS_CONNECTION_STRING=redis://redis
    ports:
      - "8000:8000"
    depends_on: 
      - mongo
      - redis
