apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-easy-rest-zero-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-easy-rest-zero-test
  template:
    spec:
      containers:
        - name: py-easy-rest-zero-test
          image: fake-image
          resources:
            requests:
              memory: 4Mi
              cpu: 0.1
            limits:
              memory: 8Mi
              cpu: 0.4
          envFrom:
          - configMapRef:
              name: py-easy-rest-zero-test-config
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: py-easy-rest-zero-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-easy-rest-zero-test
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 60
