apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml


configMapGenerator:
- name: py-easy-rest-zero-test-config
  literals: []


commonLabels:
  app: py-easy-rest-zero-test
